# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               "Fartash Faghri's Tricks"
tagline:             ''
description:         ''
url:                 http://fartashf.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Fartash Faghri
  url:               https://twitter.com/fartashfg
  email:             fartash.faghri@gmail.com
twitter_username: fartashfg
github_username: fartashf

github:
    repo: https://github.com/fartashf

gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    auto_ids: true
    syntax_highlighter: rouge
    hard_wrap: false
